// <auto-generated />
using System;
using JobHunter.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JobHunter.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(JobHunterDbContext))]
    [Migration("20260803204034_F3AddEnrichmentAiSignals")]
    partial class F3AddEnrichmentAiSignals
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JobHunter.Domain.Companies.AtsBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AtsKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("ats_kind");

                    b.Property<string>("BoardToken")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("board_token");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("evidence");

                    b.Property<DateTimeOffset?>("RetiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retired_at");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "AtsKind", "BoardToken")
                        .IsUnique()
                        .HasDatabaseName("uq_ats_bindings_live")
                        .HasFilter("retired_at IS NULL");

                    b.ToTable("ats_bindings", (string)null);
                });

            modelBuilder.Entity("JobHunter.Domain.Companies.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CanonicalDomain")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("canonical_domain");

                    b.Property<string>("CareersUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("careers_url");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<string>("EmployeeBand")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("employee_band");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<string>("HqCountry")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("hq_country");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.Property<string>("Stage")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("stage");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalDomain")
                        .IsUnique()
                        .HasDatabaseName("uq_companies_domain");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_companies_active")
                        .HasFilter("is_active");

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("JobHunter.Domain.Intelligence.Enrichment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AiUsage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ai_usage");

                    b.Property<string>("CompanyStage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("company_stage");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsContractorFriendly")
                        .HasColumnType("boolean")
                        .HasColumnName("is_contractor_friendly");

                    b.Property<bool>("IsRemote")
                        .HasColumnType("boolean")
                        .HasColumnName("is_remote");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prompt_version");

                    b.Property<string>("RoleFamily")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_family");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<string>("TimezoneBand")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("timezone_band");

                    b.Property<string>("_reasons")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("reasons");

                    b.Property<string>("_technologies")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("technologies");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.HasIndex("JobId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_enrichments_job_latest");

                    b.HasIndex("JobId", "RunId")
                        .IsUnique()
                        .HasDatabaseName("uq_enrichments_job_run");

                    b.ToTable("enrichments", (string)null);
                });

            modelBuilder.Entity("JobHunter.Domain.Jobs.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApplyUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("apply_url");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("employment_type");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("fingerprint");

                    b.Property<short>("FingerprintVersion")
                        .HasColumnType("smallint")
                        .HasColumnName("fingerprint_version");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<bool>("IsTier2")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_tier2");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Locations")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("locations");

                    b.Property<string>("NormalisedTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalised_title");

                    b.Property<Guid>("OriginRawPostingId")
                        .HasColumnType("uuid")
                        .HasColumnName("origin_raw_posting_id");

                    b.Property<DateTimeOffset?>("PostedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("posted_at");

                    b.Property<string>("PostedAtGranularity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("posted_at_granularity");

                    b.Property<string>("RemotePolicy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("remote_policy");

                    b.Property<string>("SalaryRaw")
                        .HasColumnType("text")
                        .HasColumnName("salary_raw");

                    b.Property<string>("Seniority")
                        .HasColumnType("text")
                        .HasColumnName("seniority");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid?>("SupersededBy")
                        .HasColumnType("uuid")
                        .HasColumnName("superseded_by");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("Fingerprint")
                        .IsUnique()
                        .HasDatabaseName("uq_jobs_fingerprint");

                    b.HasIndex("FirstSeenAt")
                        .HasDatabaseName("idx_jobs_first_seen")
                        .HasFilter("status = 'Live'");

                    b.HasIndex("LastSeenAt")
                        .HasDatabaseName("idx_jobs_last_seen")
                        .HasFilter("status = 'Live'");

                    b.HasIndex("CompanyId", "Status")
                        .HasDatabaseName("idx_jobs_company_status");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("JobHunter.Domain.Jobs.JobAlias", b =>
                {
                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<Guid>("RawPostingId")
                        .HasColumnType("uuid")
                        .HasColumnName("raw_posting_id");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.HasKey("JobId", "RawPostingId");

                    b.HasIndex("RawPostingId")
                        .HasDatabaseName("idx_job_aliases_raw");

                    b.HasIndex("SourceId");

                    b.ToTable("job_aliases", (string)null);
                });

            modelBuilder.Entity("JobHunter.Domain.Jobs.JobTechnology", b =>
                {
                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("Technology")
                        .HasColumnType("text")
                        .HasColumnName("technology");

                    b.Property<string>("MatchedVia")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("matched_via");

                    b.HasKey("JobId", "Technology");

                    b.HasIndex("Technology")
                        .HasDatabaseName("idx_job_technologies_tech");

                    b.ToTable("job_technologies", (string)null);
                });

            modelBuilder.Entity("JobHunter.Domain.Pipeline.Batch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("input_tokens");

                    b.Property<int>("ItemCount")
                        .HasColumnType("integer")
                        .HasColumnName("item_count");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("output_tokens");

                    b.Property<int>("PollAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("poll_attempts");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prompt_version");

                    b.Property<string>("ProviderBatchId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider_batch_id");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stage");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tier");

                    b.HasKey("Id");

                    b.HasIndex("State", "SubmittedAt")
                        .HasDatabaseName("idx_batches_pending")
                        .HasFilter("state IN ('Submitted','InProgress')");

                    b.HasIndex("RunId", "Stage", "Tier")
                        .IsUnique()
                        .HasDatabaseName("uq_batches_run_stage_tier");

                    b.ToTable("batches", (string)null);
                });

            modelBuilder.Entity("JobHunter.Domain.Pipeline.BatchItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<string>("CustomId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("custom_id");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("ParseError")
                        .HasColumnType("text")
                        .HasColumnName("parse_error");

                    b.Property<string>("RawResult")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_result");

                    b.Property<short>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("retry_count");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("BatchId", "CustomId")
                        .IsUnique()
                        .HasDatabaseName("uq_batch_items");

                    b.HasIndex("State", "RetryCount")
                        .HasDatabaseName("idx_batch_items_retry")
                        .HasFilter("state = 'ParseFailed'");

                    b.ToTable("batch_items", (string)null);
                });

            modelBuilder.Entity("JobHunter.Domain.Pipeline.CostLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<decimal>("CostUsd")
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("cost_usd");

                    b.Property<int>("InputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("input_tokens");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("output_tokens");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stage");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tier");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("RunId", "Stage", "Tier")
                        .HasDatabaseName("idx_cost_ledger_run");

                    b.ToTable("cost_ledger_entries", (string)null);
                });

            modelBuilder.Entity("JobHunter.Domain.Pipeline.Run", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("CeilingUsd")
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("ceiling_usd");

                    b.Property<DateTimeOffset>("CutoffFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cutoff_from");

                    b.Property<DateTimeOffset>("CutoffTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cutoff_to");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text")
                        .HasColumnName("failure_reason");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<int>("JobsCarriedOver")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("jobs_carried_over");

                    b.Property<int>("JobsInScope")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("jobs_in_scope");

                    b.Property<decimal>("SpentUsd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(8,4)")
                        .HasDefaultValue(0m)
                        .HasColumnName("spent_usd");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.HasKey("Id");

                    b.HasIndex("FinishedAt")
                        .HasDatabaseName("idx_runs_delivered")
                        .HasFilter("state = 'Delivered'");

                    b.ToTable("runs", (string)null);
                });

            modelBuilder.Entity("JobHunter.Domain.Postings.RawPosting", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("content_hash");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("external_id");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at");

                    b.Property<short>("HttpStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("http_status");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.HasKey("Id");

                    b.HasIndex("FetchedAt")
                        .HasDatabaseName("idx_raw_postings_fetched");

                    b.HasIndex("SourceId", "LastSeenAt")
                        .HasDatabaseName("idx_raw_postings_source_seen");

                    b.HasIndex("SourceId", "ExternalId", "ContentHash")
                        .IsUnique()
                        .HasDatabaseName("uq_raw_postings_dedup");

                    b.ToTable("raw_postings", (string)null);
                });

            modelBuilder.Entity("JobHunter.Domain.Sources.JobSource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BindingId")
                        .HasColumnType("uuid")
                        .HasColumnName("binding_id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<short>("ConsecutiveFailures")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("consecutive_failures");

                    b.Property<string>("EndpointUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("endpoint_url");

                    b.Property<DateTimeOffset?>("LastFetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_fetched_at");

                    b.Property<DateTimeOffset?>("QuarantinedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("quarantined_until");

                    b.Property<short>("RequestsPerSecond")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("requests_per_second");

                    b.HasKey("Id");

                    b.HasIndex("BindingId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("QuarantinedUntil", "LastFetchedAt")
                        .HasDatabaseName("idx_job_sources_dispatch")
                        .HasFilter("quarantined_until IS NULL");

                    b.ToTable("job_sources", (string)null);
                });

            modelBuilder.Entity("JobHunter.Domain.Sources.SourceFetchLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Detail")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("detail");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<short>("HttpStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("http_status");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("outcome");

                    b.Property<int>("PostingsChanged")
                        .HasColumnType("integer")
                        .HasColumnName("postings_changed");

                    b.Property<int>("PostingsReturned")
                        .HasColumnType("integer")
                        .HasColumnName("postings_returned");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.HasKey("Id");

                    b.HasIndex("SourceId", "StartedAt")
                        .HasDatabaseName("idx_fetch_log_source_started");

                    b.ToTable("source_fetch_log", (string)null);
                });

            modelBuilder.Entity("JobHunter.Infrastructure.Persistence.Reference.PlatformMarker", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("label");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Label")
                        .IsUnique()
                        .HasDatabaseName("uq_platform_markers_label");

                    b.ToTable("platform_markers", (string)null);
                });

            modelBuilder.Entity("JobHunter.Domain.Companies.AtsBinding", b =>
                {
                    b.HasOne("JobHunter.Domain.Companies.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobHunter.Domain.Intelligence.Enrichment", b =>
                {
                    b.HasOne("JobHunter.Domain.Jobs.Job", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobHunter.Domain.Pipeline.Run", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("JobHunter.Domain.Intelligence.AiSignals", "AiSignals", b1 =>
                        {
                            b1.Property<Guid>("EnrichmentId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("BuildsAiInfra")
                                .HasColumnType("boolean")
                                .HasColumnName("ai_builds_infra");

                            b1.Property<bool>("BuildsAiProduct")
                                .HasColumnType("boolean")
                                .HasColumnName("ai_builds_product");

                            b1.Property<bool>("IsResearch")
                                .HasColumnType("boolean")
                                .HasColumnName("ai_is_research");

                            b1.Property<bool>("UsesAiTooling")
                                .HasColumnType("boolean")
                                .HasColumnName("ai_uses_tooling");

                            b1.HasKey("EnrichmentId");

                            b1.ToTable("enrichments");

                            b1.WithOwner()
                                .HasForeignKey("EnrichmentId");
                        });

                    b.OwnsOne("JobHunter.Domain.Intelligence.SalaryEstimate", "Salary", b1 =>
                        {
                            b1.Property<Guid>("EnrichmentId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Confidence")
                                .HasColumnType("numeric(3,2)")
                                .HasColumnName("salary_confidence");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("char(3)")
                                .HasColumnName("salary_currency");

                            b1.Property<decimal>("Max")
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("salary_max");

                            b1.Property<decimal>("Min")
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("salary_min");

                            b1.Property<string>("Period")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("salary_period");

                            b1.HasKey("EnrichmentId");

                            b1.ToTable("enrichments");

                            b1.WithOwner()
                                .HasForeignKey("EnrichmentId");
                        });

                    b.Navigation("AiSignals")
                        .IsRequired();

                    b.Navigation("Salary");
                });

            modelBuilder.Entity("JobHunter.Domain.Jobs.Job", b =>
                {
                    b.HasOne("JobHunter.Domain.Companies.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("JobHunter.Domain.Jobs.SalaryRange", "Salary", b1 =>
                        {
                            b1.Property<Guid>("JobId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("char(3)")
                                .HasColumnName("salary_currency");

                            b1.Property<decimal>("Max")
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("salary_max");

                            b1.Property<decimal>("Min")
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("salary_min");

                            b1.Property<string>("Period")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("salary_period");

                            b1.HasKey("JobId");

                            b1.ToTable("jobs");

                            b1.WithOwner()
                                .HasForeignKey("JobId");
                        });

                    b.Navigation("Salary");
                });

            modelBuilder.Entity("JobHunter.Domain.Jobs.JobAlias", b =>
                {
                    b.HasOne("JobHunter.Domain.Jobs.Job", null)
                        .WithMany("Aliases")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobHunter.Domain.Postings.RawPosting", null)
                        .WithMany()
                        .HasForeignKey("RawPostingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JobHunter.Domain.Sources.JobSource", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("JobHunter.Domain.Jobs.JobTechnology", b =>
                {
                    b.HasOne("JobHunter.Domain.Jobs.Job", null)
                        .WithMany("Technologies")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobHunter.Domain.Pipeline.Batch", b =>
                {
                    b.HasOne("JobHunter.Domain.Pipeline.Run", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobHunter.Domain.Pipeline.BatchItem", b =>
                {
                    b.HasOne("JobHunter.Domain.Pipeline.Batch", null)
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobHunter.Domain.Jobs.Job", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobHunter.Domain.Pipeline.CostLedgerEntry", b =>
                {
                    b.HasOne("JobHunter.Domain.Pipeline.Batch", null)
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("JobHunter.Domain.Pipeline.Run", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobHunter.Domain.Postings.RawPosting", b =>
                {
                    b.HasOne("JobHunter.Domain.Sources.JobSource", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobHunter.Domain.Sources.JobSource", b =>
                {
                    b.HasOne("JobHunter.Domain.Companies.AtsBinding", null)
                        .WithMany()
                        .HasForeignKey("BindingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobHunter.Domain.Companies.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobHunter.Domain.Sources.SourceFetchLog", b =>
                {
                    b.HasOne("JobHunter.Domain.Sources.JobSource", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobHunter.Domain.Jobs.Job", b =>
                {
                    b.Navigation("Aliases");

                    b.Navigation("Technologies");
                });
#pragma warning restore 612, 618
        }
    }
}
