// <auto-generated />
using System;
using JobHunter.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JobHunter.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(JobHunterDbContext))]
    [Migration("20260807081508_F8AddCompanyResearch")]
    partial class F8AddCompanyResearch
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JobHunter.Domain.Applications.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AppliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at");

                    b.Property<bool>("Archived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("archived");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<DateTimeOffset>("LastActivityAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at");

                    b.Property<DateTimeOffset?>("LastReminderAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_reminder_at");

                    b.Property<string>("LastReminderCondition")
                        .HasColumnType("text")
                        .HasColumnName("last_reminder_condition");

                    b.Property<DateTimeOffset?>("NextActionAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_action_at");

                    b.Property<bool>("PostingClosed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("posting_closed");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("JobId")
                        .IsUnique()
                        .HasDatabaseName("uq_applications_job");

                    b.HasIndex("NextActionAt")
                        .HasDatabaseName("idx_applications_due")
                        .HasFilter("next_action_at IS NOT NULL AND NOT archived");

                    b.HasIndex("Status", "LastActivityAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_applications_pipeline")
                        .HasFilter("NOT archived");

                    b.ToTable("applications", (string)null);
                });

            modelBuilder.Entity("JobHunter.Domain.Applications.ApplicationNote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_notes_application");

                    b.ToTable("application_notes", (string)null);
                });

            modelBuilder.Entity("JobHunter.Domain.Applications.StatusTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<string>("Detail")
                        .HasColumnType("text")
                        .HasColumnName("detail");

                    b.Property<string>("From")
                        .HasColumnType("text")
                        .HasColumnName("from_status");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("to_status");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId", "OccurredAt")
                        .HasDatabaseName("idx_transitions_application");

                    b.HasIndex("To", "OccurredAt")
                        .HasDatabaseName("idx_transitions_outcome")
                        .HasFilter("to_status IN ('Interview','Offer','Rejected')");

                    b.ToTable("application_transitions", (string)null);
                });

            modelBuilder.Entity("JobHunter.Domain.Companies.AtsBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AtsKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("ats_kind");

                    b.Property<string>("BoardToken")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("board_token");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("evidence");

                    b.Property<DateTimeOffset?>("RetiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retired_at");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "AtsKind", "BoardToken")
                        .IsUnique()
                        .HasDatabaseName("uq_ats_bindings_live")
                        .HasFilter("retired_at IS NULL");

                    b.ToTable("ats_bindings", (string)null);
                });

            modelBuilder.Entity("JobHunter.Domain.Companies.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CanonicalDomain")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("canonical_domain");

                    b.Property<string>("CareersUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("careers_url");

                    b.Property<string>("CompBand")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("comp_band");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<string>("EmployeeBand")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("employee_band");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<string>("HqCountry")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("hq_country");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<bool?>("RemoteEmeaFriendly")
                        .HasColumnType("boolean")
                        .HasColumnName("remote_emea_friendly");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.Property<string>("Stage")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("stage");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalDomain")
                        .IsUnique()
                        .HasDatabaseName("uq_companies_domain");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_companies_active")
                        .HasFilter("is_active");

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("JobHunter.Domain.Intelligence.Enrichment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AiUsage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ai_usage");

                    b.Property<string>("CompanyStage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("company_stage");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsContractorFriendly")
                        .HasColumnType("boolean")
                        .HasColumnName("is_contractor_friendly");

                    b.Property<bool>("IsRemote")
                        .HasColumnType("boolean")
                        .HasColumnName("is_remote");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prompt_version");

                    b.Property<string>("RoleFamily")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_family");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<string>("TimezoneBand")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("timezone_band");

                    b.Property<string>("_reasons")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("reasons");

                    b.Property<string>("_technologies")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("technologies");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.HasIndex("JobId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_enrichments_job_latest");

                    b.HasIndex("JobId", "RunId")
                        .IsUnique()
                        .HasDatabaseName("uq_enrichments_job_run");

                    b.ToTable("enrichments", (string)null);
                });

            modelBuilder.Entity("JobHunter.Domain.Intelligence.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CvVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("cv_version_id");

                    b.Property<string>("InterviewProbability")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("interview_probability");

                    b.Property<bool>("IsCurrent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_current");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<short>("MatchScore")
                        .HasColumnType("smallint")
                        .HasColumnName("match_score");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prompt_version");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<string>("_missingSkills")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("missing_skills");

                    b.Property<string>("_reasons")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("reasons");

                    b.HasKey("Id");

                    b.HasIndex("CvVersionId")
                        .HasDatabaseName("idx_matches_cv_version")
                        .HasFilter("is_current");

                    b.HasIndex("ProfileId");

                    b.HasIndex("RunId");

                    b.HasIndex("JobId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_matches_current")
                        .HasFilter("is_current");

                    b.HasIndex("JobId", "RunId", "ProfileId")
                        .IsUnique()
                        .HasDatabaseName("uq_matches_job_run_profile");

                    b.ToTable("matches", (string)null);
                });

            modelBuilder.Entity("JobHunter.Domain.Intelligence.ReMatchQueueItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Consumed")
                        .HasColumnType("boolean")
                        .HasColumnName("consumed");

                    b.Property<Guid>("CvVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("cv_version_id");

                    b.Property<DateTimeOffset>("EnqueuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enqueued_at");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tier");

                    b.HasKey("Id");

                    b.HasIndex("CvVersionId");

                    b.HasIndex("JobId")
                        .IsUnique()
                        .HasDatabaseName("uq_re_match_queue_open")
                        .HasFilter("NOT consumed");

                    b.ToTable("re_match_queue", (string)null);
                });

            modelBuilder.Entity("JobHunter.Domain.Intelligence.Score", b =>
                {
                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("computed_at");

                    b.Property<decimal>("FinalScore")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("final_score");

                    b.Property<Guid?>("PreferenceModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("preference_model_id");

                    b.Property<bool>("Suppressed")
                        .HasColumnType("boolean")
                        .HasColumnName("suppressed");

                    b.Property<string>("SuppressionReason")
                        .HasColumnType("text")
                        .HasColumnName("suppression_reason");

                    b.HasKey("JobId", "RunId");

                    b.HasIndex("RunId")
                        .HasDatabaseName("idx_scores_suppressed")
                        .HasFilter("suppressed");

                    b.HasIndex("RunId", "FinalScore")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_scores_run_final")
                        .HasFilter("NOT suppressed");

                    b.ToTable("scores", (string)null);
                });

            modelBuilder.Entity("JobHunter.Domain.Jobs.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApplyUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("apply_url");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("employment_type");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("fingerprint");

                    b.Property<short>("FingerprintVersion")
                        .HasColumnType("smallint")
                        .HasColumnName("fingerprint_version");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<bool>("IsTier2")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_tier2");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Locations")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("locations");

                    b.Property<string>("NormalisedTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalised_title");

                    b.Property<Guid>("OriginRawPostingId")
                        .HasColumnType("uuid")
                        .HasColumnName("origin_raw_posting_id");

                    b.Property<DateTimeOffset?>("PostedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("posted_at");

                    b.Property<string>("PostedAtGranularity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("posted_at_granularity");

                    b.Property<string>("RemotePolicy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("remote_policy");

                    b.Property<string>("SalaryRaw")
                        .HasColumnType("text")
                        .HasColumnName("salary_raw");

                    b.Property<string>("Seniority")
                        .HasColumnType("text")
                        .HasColumnName("seniority");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid?>("SupersededBy")
                        .HasColumnType("uuid")
                        .HasColumnName("superseded_by");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("Fingerprint")
                        .IsUnique()
                        .HasDatabaseName("uq_jobs_fingerprint");

                    b.HasIndex("FirstSeenAt")
                        .HasDatabaseName("idx_jobs_first_seen")
                        .HasFilter("status = 'Live'");

                    b.HasIndex("LastSeenAt")
                        .HasDatabaseName("idx_jobs_last_seen")
                        .HasFilter("status = 'Live'");

                    b.HasIndex("CompanyId", "Status")
                        .HasDatabaseName("idx_jobs_company_status");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("JobHunter.Domain.Jobs.JobAlias", b =>
                {
                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<Guid>("RawPostingId")
                        .HasColumnType("uuid")
                        .HasColumnName("raw_posting_id");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.HasKey("JobId", "RawPostingId");

                    b.HasIndex("RawPostingId")
                        .HasDatabaseName("idx_job_aliases_raw");

                    b.HasIndex("SourceId");

                    b.ToTable("job_aliases", (string)null);
                });

            modelBuilder.Entity("JobHunter.Domain.Jobs.JobTechnology", b =>
                {
                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("Technology")
                        .HasColumnType("text")
                        .HasColumnName("technology");

                    b.Property<string>("MatchedVia")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("matched_via");

                    b.HasKey("JobId", "Technology");

                    b.HasIndex("Technology")
                        .HasDatabaseName("idx_job_technologies_tech");

                    b.ToTable("job_technologies", (string)null);
                });

            modelBuilder.Entity("JobHunter.Domain.Pipeline.Batch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("input_tokens");

                    b.Property<int>("ItemCount")
                        .HasColumnType("integer")
                        .HasColumnName("item_count");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("output_tokens");

                    b.Property<int>("PollAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("poll_attempts");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prompt_version");

                    b.Property<string>("ProviderBatchId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider_batch_id");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stage");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tier");

                    b.HasKey("Id");

                    b.HasIndex("State", "SubmittedAt")
                        .HasDatabaseName("idx_batches_pending")
                        .HasFilter("state IN ('Submitted','InProgress')");

                    b.HasIndex("RunId", "Stage", "Tier")
                        .IsUnique()
                        .HasDatabaseName("uq_batches_run_stage_tier");

                    b.ToTable("batches", (string)null);
                });

            modelBuilder.Entity("JobHunter.Domain.Pipeline.BatchItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<string>("CustomId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("custom_id");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("ParseError")
                        .HasColumnType("text")
                        .HasColumnName("parse_error");

                    b.Property<string>("RawResult")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_result");

                    b.Property<short>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("retry_count");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("BatchId", "CustomId")
                        .IsUnique()
                        .HasDatabaseName("uq_batch_items");

                    b.HasIndex("State", "RetryCount")
                        .HasDatabaseName("idx_batch_items_retry")
                        .HasFilter("state = 'ParseFailed'");

                    b.ToTable("batch_items", (string)null);
                });

            modelBuilder.Entity("JobHunter.Domain.Pipeline.CostLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<decimal>("CostUsd")
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("cost_usd");

                    b.Property<int>("InputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("input_tokens");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("output_tokens");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stage");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tier");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("RunId", "Stage", "Tier")
                        .HasDatabaseName("idx_cost_ledger_run");

                    b.ToTable("cost_ledger_entries", (string)null);
                });

            modelBuilder.Entity("JobHunter.Domain.Pipeline.Run", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("CeilingUsd")
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("ceiling_usd");

                    b.Property<DateTimeOffset>("CutoffFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cutoff_from");

                    b.Property<DateTimeOffset>("CutoffTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cutoff_to");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text")
                        .HasColumnName("failure_reason");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<int>("JobsCarriedOver")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("jobs_carried_over");

                    b.Property<int>("JobsInScope")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("jobs_in_scope");

                    b.Property<decimal>("SpentUsd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(8,4)")
                        .HasDefaultValue(0m)
                        .HasColumnName("spent_usd");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.HasKey("Id");

                    b.HasIndex("FinishedAt")
                        .HasDatabaseName("idx_runs_delivered")
                        .HasFilter("state = 'Delivered'");

                    b.ToTable("runs", (string)null);
                });

            modelBuilder.Entity("JobHunter.Domain.Postings.RawPosting", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("content_hash");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("external_id");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at");

                    b.Property<short>("HttpStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("http_status");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.HasKey("Id");

                    b.HasIndex("FetchedAt")
                        .HasDatabaseName("idx_raw_postings_fetched");

                    b.HasIndex("SourceId", "LastSeenAt")
                        .HasDatabaseName("idx_raw_postings_source_seen");

                    b.HasIndex("SourceId", "ExternalId", "ContentHash")
                        .IsUnique()
                        .HasDatabaseName("uq_raw_postings_dedup");

                    b.ToTable("raw_postings", (string)null);
                });

            modelBuilder.Entity("JobHunter.Domain.Preferences.PreferenceModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at");

                    b.Property<DateTimeOffset>("FittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fitted_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("SignalCount")
                        .HasColumnType("integer")
                        .HasColumnName("signal_count");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Version")
                        .IsUnique()
                        .HasDatabaseName("uq_preference_models_version");

                    b.ToTable("preference_models", (string)null);
                });

            modelBuilder.Entity("JobHunter.Domain.Preferences.PreferenceWeight", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Dimension")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dimension");

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean")
                        .HasColumnName("disabled");

                    b.Property<DateTimeOffset?>("DisabledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_at");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("model_id");

                    b.Property<decimal>("PositiveRate")
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("positive_rate");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("weight");

                    b.Property<string>("_supportingSignalIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("supporting_signal_ids");

                    b.HasKey("Id");

                    b.HasIndex("ModelId", "Dimension", "Value")
                        .HasDatabaseName("idx_preference_weights_lookup")
                        .HasFilter("NOT disabled");

                    b.ToTable("preference_weights", (string)null);
                });

            modelBuilder.Entity("JobHunter.Domain.Preferences.Signal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<string>("JobFacts")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("job_facts");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric(3,1)")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt")
                        .IsDescending()
                        .HasDatabaseName("idx_signals_window");

                    b.HasIndex("Kind", "OccurredAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_signals_kind");

                    b.HasIndex("JobId", "Kind", "OccurredAt")
                        .IsUnique()
                        .HasDatabaseName("uq_signals_action");

                    b.ToTable("signals", (string)null);
                });

            modelBuilder.Entity("JobHunter.Domain.Preferences.SuppressionOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Dimension")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dimension");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mode");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("Dimension", "Value")
                        .IsUnique()
                        .HasDatabaseName("uq_suppression_overrides");

                    b.ToTable("suppression_overrides", (string)null);
                });

            modelBuilder.Entity("JobHunter.Domain.Profiles.CvVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("content_hash");

                    b.Property<string>("ExtractedText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("extracted_text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("media_type");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<int>("SizeBytes")
                        .HasColumnType("integer")
                        .HasColumnName("size_bytes");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<short>("Version")
                        .HasColumnType("smallint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "ContentHash")
                        .IsUnique()
                        .HasDatabaseName("uq_cv_versions_hash");

                    b.ToTable("cv_versions", (string)null);
                });

            modelBuilder.Entity("JobHunter.Domain.Profiles.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DesiredAiUsageFloor")
                        .HasColumnType("text")
                        .HasColumnName("desired_ai_usage_floor");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal?>("SalaryFloor")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("salary_floor");

                    b.Property<string>("SalaryFloorCurrency")
                        .HasColumnType("char(3)")
                        .HasColumnName("salary_floor_currency");

                    b.Property<string>("TimezoneBand")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("timezone_band");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("_employmentTypes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("employment_types");

                    b.Property<string>("_preferredCountries")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("preferred_countries");

                    b.Property<string>("_targetRoleFamilies")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("target_role_families");

                    b.Property<string>("_targetTitles")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("target_titles");

                    b.HasKey("Id");

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("JobHunter.Domain.Reporting.DeliveryRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CardKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("card_key");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<DateTimeOffset>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<long?>("TelegramMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_message_id");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "ChatId")
                        .HasDatabaseName("idx_delivery_log_run_chat");

                    b.HasIndex("RunId", "ChatId", "CardKey")
                        .IsUnique()
                        .HasDatabaseName("uq_delivery_log");

                    b.ToTable("delivery_log", (string)null);
                });

            modelBuilder.Entity("JobHunter.Domain.Reporting.Digest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AnalysedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("analysed_count");

                    b.Property<decimal?>("AvgSalaryUsd")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("avg_salary_usd");

                    b.Property<int>("CarriedOverCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("carried_over_count");

                    b.Property<int>("CompaniesChecked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("companies_checked");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<bool>("LearningEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("learning_enabled");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mode");

                    b.Property<string>("Narrative")
                        .HasColumnType("text")
                        .HasColumnName("narrative");

                    b.Property<string>("NarrativeSource")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("narrative_source");

                    b.Property<string>("PromptVersion")
                        .HasColumnType("text")
                        .HasColumnName("prompt_version");

                    b.Property<int>("RestoredCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("restored_count");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<int>("StrongMatches")
                        .HasColumnType("integer")
                        .HasColumnName("strong_matches");

                    b.Property<int>("SuppressedCount")
                        .HasColumnType("integer")
                        .HasColumnName("suppressed_count");

                    b.Property<int>("TotalNewJobs")
                        .HasColumnType("integer")
                        .HasColumnName("total_new_jobs");

                    b.Property<string>("_degradedSources")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("degraded_sources");

                    b.Property<string>("_suppressionBreakdown")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("suppression_breakdown");

                    b.HasKey("Id");

                    b.HasIndex("RunId")
                        .IsUnique()
                        .HasDatabaseName("uq_digests_run");

                    b.ToTable("digests", (string)null);
                });

            modelBuilder.Entity("JobHunter.Domain.Reporting.DigestCard", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("ApplyUrlVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("apply_url_verified");

                    b.Property<Guid>("DigestId")
                        .HasColumnType("uuid")
                        .HasColumnName("digest_id");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("card_key");

                    b.Property<short>("Rank")
                        .HasColumnType("smallint")
                        .HasColumnName("rank");

                    b.Property<decimal>("Score")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("score");

                    b.Property<string>("_groupedJobIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("grouped_job_ids");

                    b.Property<string>("_reasons")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("reasons");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("DigestId", "JobId")
                        .IsUnique()
                        .HasDatabaseName("uq_digest_cards_job");

                    b.HasIndex("DigestId", "Key")
                        .IsUnique()
                        .HasDatabaseName("uq_digest_cards_key");

                    b.HasIndex("DigestId", "Rank")
                        .HasDatabaseName("idx_digest_cards_rank");

                    b.ToTable("digest_cards", (string)null);
                });

            modelBuilder.Entity("JobHunter.Domain.Research.CompanyResearch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ClaimsDiscarded")
                        .HasColumnType("integer")
                        .HasColumnName("claims_discarded");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prompt_version");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<string>("_categoriesUnavailable")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("categories_unavailable");

                    b.Property<string>("categories_covered")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("categories_covered");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.HasIndex("CompanyId", "GeneratedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_research_company_latest");

                    b.HasIndex("CompanyId", "RunId")
                        .IsUnique()
                        .HasDatabaseName("uq_research_company_run");

                    b.ToTable("company_research", (string)null);
                });

            modelBuilder.Entity("JobHunter.Domain.Research.ResearchClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("Claim")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("claim");

                    b.Property<bool>("IsWarning")
                        .HasColumnType("boolean")
                        .HasColumnName("is_warning");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<Guid>("research_id")
                        .HasColumnType("uuid")
                        .HasColumnName("research_id");

                    b.HasKey("Id");

                    b.HasIndex("research_id")
                        .HasDatabaseName("idx_claims_warnings")
                        .HasFilter("is_warning");

                    b.HasIndex("research_id", "Category")
                        .HasDatabaseName("idx_claims_research");

                    b.ToTable("research_claims", (string)null);
                });

            modelBuilder.Entity("JobHunter.Domain.Research.ResearchSource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<int>("TextLength")
                        .HasColumnType("integer")
                        .HasColumnName("text_length");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<Guid>("research_id")
                        .HasColumnType("uuid")
                        .HasColumnName("research_id");

                    b.HasKey("Id");

                    b.HasAlternateKey("research_id", "Id");

                    b.HasIndex("research_id", "Category")
                        .HasDatabaseName("idx_sources_research");

                    b.HasIndex("research_id", "Url")
                        .IsUnique()
                        .HasDatabaseName("uq_sources_url");

                    b.ToTable("research_sources", (string)null);
                });

            modelBuilder.Entity("JobHunter.Domain.Sources.JobSource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BindingId")
                        .HasColumnType("uuid")
                        .HasColumnName("binding_id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<short>("ConsecutiveFailures")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("consecutive_failures");

                    b.Property<string>("EndpointUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("endpoint_url");

                    b.Property<DateTimeOffset?>("LastFetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_fetched_at");

                    b.Property<DateTimeOffset?>("QuarantinedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("quarantined_until");

                    b.Property<short>("RequestsPerSecond")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("requests_per_second");

                    b.HasKey("Id");

                    b.HasIndex("BindingId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("QuarantinedUntil", "LastFetchedAt")
                        .HasDatabaseName("idx_job_sources_dispatch")
                        .HasFilter("quarantined_until IS NULL");

                    b.ToTable("job_sources", (string)null);
                });

            modelBuilder.Entity("JobHunter.Domain.Sources.SourceFetchLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Detail")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("detail");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<short>("HttpStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("http_status");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("outcome");

                    b.Property<int>("PostingsChanged")
                        .HasColumnType("integer")
                        .HasColumnName("postings_changed");

                    b.Property<int>("PostingsReturned")
                        .HasColumnType("integer")
                        .HasColumnName("postings_returned");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.HasKey("Id");

                    b.HasIndex("SourceId", "StartedAt")
                        .HasDatabaseName("idx_fetch_log_source_started");

                    b.ToTable("source_fetch_log", (string)null);
                });

            modelBuilder.Entity("JobHunter.Infrastructure.Persistence.Preferences.LearningState", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("learning_state", (string)null);
                });

            modelBuilder.Entity("JobHunter.Infrastructure.Persistence.Reference.PlatformMarker", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("label");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Label")
                        .IsUnique()
                        .HasDatabaseName("uq_platform_markers_label");

                    b.ToTable("platform_markers", (string)null);
                });

            modelBuilder.Entity("JobHunter.Domain.Applications.Application", b =>
                {
                    b.HasOne("JobHunter.Domain.Jobs.Job", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobHunter.Domain.Applications.ApplicationNote", b =>
                {
                    b.HasOne("JobHunter.Domain.Applications.Application", null)
                        .WithMany("Notes")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobHunter.Domain.Applications.StatusTransition", b =>
                {
                    b.HasOne("JobHunter.Domain.Applications.Application", null)
                        .WithMany("Transitions")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobHunter.Domain.Companies.AtsBinding", b =>
                {
                    b.HasOne("JobHunter.Domain.Companies.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobHunter.Domain.Intelligence.Enrichment", b =>
                {
                    b.HasOne("JobHunter.Domain.Jobs.Job", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobHunter.Domain.Pipeline.Run", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("JobHunter.Domain.Intelligence.AiSignals", "AiSignals", b1 =>
                        {
                            b1.Property<Guid>("EnrichmentId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("BuildsAiInfra")
                                .HasColumnType("boolean")
                                .HasColumnName("ai_builds_infra");

                            b1.Property<bool>("BuildsAiProduct")
                                .HasColumnType("boolean")
                                .HasColumnName("ai_builds_product");

                            b1.Property<bool>("IsResearch")
                                .HasColumnType("boolean")
                                .HasColumnName("ai_is_research");

                            b1.Property<bool>("UsesAiTooling")
                                .HasColumnType("boolean")
                                .HasColumnName("ai_uses_tooling");

                            b1.HasKey("EnrichmentId");

                            b1.ToTable("enrichments");

                            b1.WithOwner()
                                .HasForeignKey("EnrichmentId");
                        });

                    b.OwnsOne("JobHunter.Domain.Intelligence.SalaryEstimate", "Salary", b1 =>
                        {
                            b1.Property<Guid>("EnrichmentId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Confidence")
                                .HasColumnType("numeric(3,2)")
                                .HasColumnName("salary_confidence");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("char(3)")
                                .HasColumnName("salary_currency");

                            b1.Property<decimal>("Max")
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("salary_max");

                            b1.Property<decimal>("Min")
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("salary_min");

                            b1.Property<string>("Period")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("salary_period");

                            b1.HasKey("EnrichmentId");

                            b1.ToTable("enrichments");

                            b1.WithOwner()
                                .HasForeignKey("EnrichmentId");
                        });

                    b.Navigation("AiSignals")
                        .IsRequired();

                    b.Navigation("Salary");
                });

            modelBuilder.Entity("JobHunter.Domain.Intelligence.Match", b =>
                {
                    b.HasOne("JobHunter.Domain.Profiles.CvVersion", null)
                        .WithMany()
                        .HasForeignKey("CvVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobHunter.Domain.Jobs.Job", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobHunter.Domain.Profiles.Profile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobHunter.Domain.Pipeline.Run", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("JobHunter.Domain.Intelligence.SalaryExpectation", "SalaryExpectation", b1 =>
                        {
                            b1.Property<Guid>("MatchId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("char(3)")
                                .HasColumnName("salary_expectation_currency");

                            b1.Property<decimal>("Max")
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("salary_expectation_max");

                            b1.Property<decimal>("Min")
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("salary_expectation_min");

                            b1.HasKey("MatchId");

                            b1.ToTable("matches");

                            b1.WithOwner()
                                .HasForeignKey("MatchId");
                        });

                    b.Navigation("SalaryExpectation");
                });

            modelBuilder.Entity("JobHunter.Domain.Intelligence.ReMatchQueueItem", b =>
                {
                    b.HasOne("JobHunter.Domain.Profiles.CvVersion", null)
                        .WithMany()
                        .HasForeignKey("CvVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobHunter.Domain.Jobs.Job", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobHunter.Domain.Intelligence.Score", b =>
                {
                    b.HasOne("JobHunter.Domain.Jobs.Job", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobHunter.Domain.Pipeline.Run", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("JobHunter.Domain.Intelligence.ScoreComponents", "Components", b1 =>
                        {
                            b1.Property<Guid>("ScoreJobId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("ScoreRunId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Alignment")
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("alignment_component");

                            b1.Property<decimal>("AntiGoalMultiplier")
                                .HasColumnType("numeric(3,2)")
                                .HasColumnName("anti_goal_multiplier");

                            b1.Property<decimal>("ConfidenceMultiplier")
                                .HasColumnType("numeric(3,2)")
                                .HasColumnName("confidence_multiplier");

                            b1.Property<decimal>("Freshness")
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("freshness_component");

                            b1.Property<decimal>("Match")
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("match_component");

                            b1.Property<decimal>("Preference")
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("preference_component");

                            b1.HasKey("ScoreJobId", "ScoreRunId");

                            b1.ToTable("scores");

                            b1.WithOwner()
                                .HasForeignKey("ScoreJobId", "ScoreRunId");
                        });

                    b.Navigation("Components")
                        .IsRequired();
                });

            modelBuilder.Entity("JobHunter.Domain.Jobs.Job", b =>
                {
                    b.HasOne("JobHunter.Domain.Companies.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("JobHunter.Domain.Jobs.SalaryRange", "Salary", b1 =>
                        {
                            b1.Property<Guid>("JobId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("char(3)")
                                .HasColumnName("salary_currency");

                            b1.Property<decimal>("Max")
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("salary_max");

                            b1.Property<decimal>("Min")
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("salary_min");

                            b1.Property<string>("Period")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("salary_period");

                            b1.HasKey("JobId");

                            b1.ToTable("jobs");

                            b1.WithOwner()
                                .HasForeignKey("JobId");
                        });

                    b.Navigation("Salary");
                });

            modelBuilder.Entity("JobHunter.Domain.Jobs.JobAlias", b =>
                {
                    b.HasOne("JobHunter.Domain.Jobs.Job", null)
                        .WithMany("Aliases")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobHunter.Domain.Postings.RawPosting", null)
                        .WithMany()
                        .HasForeignKey("RawPostingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JobHunter.Domain.Sources.JobSource", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("JobHunter.Domain.Jobs.JobTechnology", b =>
                {
                    b.HasOne("JobHunter.Domain.Jobs.Job", null)
                        .WithMany("Technologies")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobHunter.Domain.Pipeline.Batch", b =>
                {
                    b.HasOne("JobHunter.Domain.Pipeline.Run", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobHunter.Domain.Pipeline.BatchItem", b =>
                {
                    b.HasOne("JobHunter.Domain.Pipeline.Batch", null)
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobHunter.Domain.Jobs.Job", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobHunter.Domain.Pipeline.CostLedgerEntry", b =>
                {
                    b.HasOne("JobHunter.Domain.Pipeline.Batch", null)
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("JobHunter.Domain.Pipeline.Run", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobHunter.Domain.Postings.RawPosting", b =>
                {
                    b.HasOne("JobHunter.Domain.Sources.JobSource", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobHunter.Domain.Preferences.PreferenceWeight", b =>
                {
                    b.HasOne("JobHunter.Domain.Preferences.PreferenceModel", null)
                        .WithMany("Weights")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobHunter.Domain.Preferences.Signal", b =>
                {
                    b.HasOne("JobHunter.Domain.Jobs.Job", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobHunter.Domain.Profiles.CvVersion", b =>
                {
                    b.HasOne("JobHunter.Domain.Profiles.Profile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobHunter.Domain.Reporting.DeliveryRecord", b =>
                {
                    b.HasOne("JobHunter.Domain.Pipeline.Run", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobHunter.Domain.Reporting.Digest", b =>
                {
                    b.HasOne("JobHunter.Domain.Pipeline.Run", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobHunter.Domain.Reporting.DigestCard", b =>
                {
                    b.HasOne("JobHunter.Domain.Reporting.Digest", null)
                        .WithMany("Cards")
                        .HasForeignKey("DigestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobHunter.Domain.Jobs.Job", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobHunter.Domain.Research.CompanyResearch", b =>
                {
                    b.HasOne("JobHunter.Domain.Companies.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobHunter.Domain.Pipeline.Run", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobHunter.Domain.Research.ResearchClaim", b =>
                {
                    b.HasOne("JobHunter.Domain.Research.CompanyResearch", null)
                        .WithMany("Claims")
                        .HasForeignKey("research_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobHunter.Domain.Research.ResearchSource", b =>
                {
                    b.HasOne("JobHunter.Domain.Research.CompanyResearch", null)
                        .WithMany("Sources")
                        .HasForeignKey("research_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobHunter.Domain.Sources.JobSource", b =>
                {
                    b.HasOne("JobHunter.Domain.Companies.AtsBinding", null)
                        .WithMany()
                        .HasForeignKey("BindingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobHunter.Domain.Companies.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobHunter.Domain.Sources.SourceFetchLog", b =>
                {
                    b.HasOne("JobHunter.Domain.Sources.JobSource", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobHunter.Domain.Applications.Application", b =>
                {
                    b.Navigation("Notes");

                    b.Navigation("Transitions");
                });

            modelBuilder.Entity("JobHunter.Domain.Jobs.Job", b =>
                {
                    b.Navigation("Aliases");

                    b.Navigation("Technologies");
                });

            modelBuilder.Entity("JobHunter.Domain.Preferences.PreferenceModel", b =>
                {
                    b.Navigation("Weights");
                });

            modelBuilder.Entity("JobHunter.Domain.Reporting.Digest", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("JobHunter.Domain.Research.CompanyResearch", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("Sources");
                });
#pragma warning restore 612, 618
        }
    }
}
